[package]
name = "gpsfitnessapp"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1.24.1", features = ["macros"] }
serde = "1.0.136"
warp = "0.3.3"
mongodb = { version = "2.3.1"}
chrono = "0.4.23"
futures-util = "0.3"