services:
  gpsfitnessapp:
    image: rust-debian
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - "mongodata:/data/db"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
volumes:
  mongodata: